// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Post struct {
	ID            int64
	AuthorID      int64
	Content       string
	Timestamp     string
	Ip            string
	ImageFilename sql.NullString
}

type User struct {
	ID       int64
	Username string
	Password string
	IsAdmin  int64
}
